server:
  port: 8002

spring:
  application:
    name: es-server
  profiles:
    active: dev
  # 开启虚拟线程
  threads:
    virtual:
      enabled: true

sano:
  # all提供查询并启用同步；query同样提供查询，但关闭所有同步任务和流水线。
  server-mode: all
  es:
