spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 2
          max-wait: 2000ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.128.144.26:3306/sano?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Chongqing&allowPublicKeyRetrieval=true
    username: ${MYSQL_UNM:root}
    password: ${MYSQL_PWD:SADFH28!asoaignljASjacoOs}

sano:
  es:
    uris: ${ES_URIS:127.0.0.1:9201}
    username: ${ES_USERNAME:elastic}
    password: ${ES_PASSWORD:es2peter}
    socket-timeout: 600000
    connection-timeout: 500000
    connection-request-timeout: 5000
    max-conn-total: 100
    max-conn-per-route: 20


